# Generated by Django 5.1.2 on 2024-10-22 12:15

import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrn', models.CharField(max_length=18, validators=[organization.models.validate_numeric_string])),
            ],
        ),
    ]
